WITH CAR_HISTORY AS
(SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31')

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_HISTORY GROUP BY CAR_ID HAVING COUNT(CAR_ID) >= 5)
GROUP BY CAR_ID, MONTH
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC